openapi: 3.0.0
info:
  title: Payment Service API
  version: 1.0.0
  description: API for payment processing

servers:
  - url: http://localhost:8081/api/v1

paths:
  /balance:
    get:
      operationId: getBalance
      responses:
        '200':
          description: Balance retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
  
  /payment:
    post:
      operationId: processPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: Payment processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'

components:
  schemas:
    BalanceResponse:
      type: object
      properties:
        balance:
          type: number
          format: double
          example: 1000.0
    
    PaymentRequest:
      type: object
      required:
        - amount
      properties:
        amount:
          type: number
          format: double
          example: 150.0
    
    PaymentResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Payment successful"
        remainingBalance:
          type: number
          format: double
          example: 850.0