spring:
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 120000

payment:
  service:
    url: http://localhost:8081/api/v1

logging:
  level:
    com.shop.spring.data.intershop: DEBUG
    com.shop.main.client: DEBUG
    org.springframework.web.reactive.function.client: DEBUG